spring.application.name=TransitData
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/frank
spring.datasource.username=postgres
spring.datasource.password=frank
spring.jpa.hibernate.ddl-auto=update